apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - argo-application.yaml

  - sealed-docker-registry-harbor.yaml
  - sealed-google-analytics.yaml
  - sealed-rollbar.yaml

  - cv
