---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: redis-secret
  namespace: cv-philiplehmann
spec:
  encryptedData:
    REDIS_URL: AgCQJsAnIHYIrYqH4k4OVg4AiOHOEa1RrJA3AiRravPbM9r+1GWqCdZFy3XWW5yTR6bD0qeLOv1mbTPbNixj5UVlvdaPZyGuJmr+KdvWlwtlSE0uri2PIBSN12Ckim0KaUbGZApxVt6d1hWV+B2hKlcsM1pEMW88CY6dZ5ag6WtC0OrgQXnx3aBszDLfQ4iLHiBga3C5l3EriJNqxGLzKxeJz58m+J25eQq/PlLqeddgrFvIu+N1RX2xxDC7UmJwKMOakJIr6pl7hb51J/du6Ck1Ed/gn0yfCRSiqdYCEOkl7prkOe/CXnWNhXBE1CX7TyUezogphwrj04q56lmUyhPl+JjWUfnMqdK6MwSQ07HUD8dpIl6rjmJX7ZdsdZTx86Nyd2rJQh466TQlDF8D+xozg+iP1fK+HXzhkivh4Lrwwb1lVm7Gv1c92qSDTX2Pv7PCbHnbafljKGTCU6DeQO2D+Wdz+jiBRIcVyhqQsTVlSfqZucA4w4rO9nbsjQS4HvvaZhGsGJ/9fE7E/od+/I9lJ2Gh36AseDH/2Rn8zkBMzhcmiRbqEJ7buaaEXwbPWwnbNr50z4F+LifpI4fYeL4dFcUbcFv1vkf2OFFHC79DhtkTwvTHc1Z3AdA0Rwh2LxeUDGezCh6bQ1zxMYvmoSJj6bNCuqLZcxpnOZygwfQn/Rl5/C2SxllmkfGZ9p8k67P2i5JdwCFnNtGb00O4+XzsejTvRn/83Nyhp8jdy//RY2gBsWNWFWekGmJ92m4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: redis-secret
      namespace: cv-philiplehmann
