---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: docker-registry-harbor
  namespace: cv-philiplehmann
spec:
  encryptedData:
    .dockerconfigjson: AgARpPrtv758EZqajtbKZJWANNSKyy8zmOCRGcylDlBcYlp312PjkgPaJaEr9xz78/9fmwADRxmKFZZESYmP1O1pXLrcHyEm+XOJGXhlus2E/Ls2/k5bmfDAwJbX+CpDigpNdfrb9tv3/unYALNeqst6S2VikWlNtNeIChPkhZowNc6U2EglWAhdvNE9BUlSyEadlHpDM0TsG8WZyTv5zDM3jN0yp+XC567g63Q4vb7p3Mo6ZACWf9xC6l21bINrjgBM1hadn/pgDR3ISmR+k5U7MGD+f9sFqcBDEdLtMYEe+u/dLFQfLW8NQ2a5Wy1GyInqFVOq/UGj2epNlB0er4vy0PbkAZZ2X/vp7gLZOh7kOiVqBdDIMNFP5phiIIJxcJX3ERgk9kJzl8svPoTX7hfJOhtpmVapisxMDLmDw8zlobJWUCQPRCpSEDyCbnx663IAV+h8VJseZD8OlNjOjQb1p2fYijN8L/+H1VFmplTNfh4kuPMT4r77jXH/jWQz4k1RskDW5iFErOVSDHICvSRm1cjHOA4d0KWVZkaxpzLPLAdsWzJsQvg8blxAYiAGBR0pVmjJNc9F1zqJKTW5eSnpaTESuhPloWLG4K/1ky/ZHTeBeiQDVYQGsrN48TjCSLQWc6/AR17tHHeLx5pX7BDM3G8BO1jCoMfhrzKRYmywUvIqwNkYNgkSnjcdOhk2lLEyCLF8cQBVhkDqFra4QdO9A5KlJZzo/gc41hHlEdcxWsBM9mUvO/RiAQ80PqSZGuD6iRaFwDswZixzQHIY6TMnZfRmzftyjIcHG6b6FLTN2O0jKgUAgjMtGRXDoKWjKncX1sFTKtM7boTfyGQJO4/7dmur2GePtUaW
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:.dockerconfigjson: {}
          f:type: {}
        manager: agent
        operation: Update
        time: "2023-09-05T19:39:40Z"
      name: docker-registry-harbor
      namespace: cv-philiplehmann
