export const icons = {
  apollo: { name: 'Apollo GraphQL', icon: 'apollo.svg', url: 'https://www.apollographql.com/' },
  argocd: { name: 'ArgoCD', icon: 'argocd.svg', url: 'https://argo-cd.readthedocs.io/' },
  auth0: { name: 'Auth0', icon: 'auth0.svg', url: 'https://auth0.com' },
  bitbucket: {
    name: 'BitBucket',
    icon: 'bitbucket.svg',
    url: 'https://bitbucket.org/',
  },
  c: { name: 'C', icon: 'c.png', url: 'https://en.wikipedia.org/wiki/C_(programming_language)' },
  csharp: { name: 'C#', icon: 'csharp.svg', url: 'https://dotnet.microsoft.com/en-us/languages/csharp' },
  cpp: { name: 'C++', icon: 'cpp.svg', url: 'https://en.wikipedia.org/wiki/C%2B%2B' },
  css: { name: 'CSS3', icon: 'css3.svg', url: 'https://en.wikipedia.org/wiki/CSS' },
  devops: { name: 'DevOps', icon: 'devops.svg', url: 'https://en.wikipedia.org/wiki/DevOps' },
  docker: { name: 'Docker', icon: 'docker.svg', url: 'https://www.docker.com/' },
  eck: {
    name: 'ECK',
    icon: 'elastic.svg',
    url: 'https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-quickstart.html',
  },
  elasticsearch: {
    name: 'ElasticSearch',
    icon: 'elasticsearch.svg',
    url: 'https://www.elastic.co/downloads/elasticsearch',
  },
  kibana: {
    name: 'Kibana',
    icon: 'kibana.svg',
    url: 'https://www.elastic.co/kibana',
  },
  ember: { name: 'EmberJS', icon: 'ember.svg', url: 'https://emberjs.com/' },
  es6: { name: 'ES6', icon: 'es6.svg', url: 'https://en.wikipedia.org/wiki/ECMAScript' },
  flow: { name: 'Flow', icon: 'flow.svg', url: 'https://flow.org/' },
  harbor: { name: 'Harbor', icon: 'harbor.svg', url: 'https://goharbor.io/' },
  html: { name: 'HTML5', icon: 'html5.svg', url: 'https://de.wikipedia.org/wiki/Hypertext_Markup_Language' },
  java: { name: 'Java', icon: 'java.svg', url: 'https://www.java.com/de/' },
  javascript: {
    name: 'Javascript',
    icon: 'javascript.svg',
    url: 'https://en.wikipedia.org/wiki/JavaScript',
  },
  jenkins: { name: 'Jenkins', icon: 'jenkins.svg', url: 'https://www.jenkins.io/' },
  jira: { name: 'Jira', icon: 'jira.svg', url: 'https://www.atlassian.com/software/jira' },
  kubernetes: { name: 'Kubernets', icon: 'kubernetes.svg', url: 'https://kubernetes.io/' },
  mui: { name: 'MUI', icon: 'material-ui.svg', url: 'https://mui.com/' },
  nestjs: { name: 'NestJS', icon: 'nestjs.svg', url: 'https://nestjs.com/' },
  nx: { name: 'NX', icon: 'nx.svg', url: 'https://nx.dev/' },
  prisma: { name: 'Prisma.io', icon: 'prisma.svg', url: 'https://www.prisma.io/' },
  redis: { name: 'Redis', icon: 'redis.svg', url: 'https://redis.io/' },
  'redis-cluster': { name: 'Redis Cluster', icon: 'redis.svg', url: 'https://redis.io/' },
  rails: { name: 'Ruby on Rails', icon: 'rails.svg', url: 'https://rubyonrails.org/' },
  ruby: { name: 'Ruby', icon: 'ruby.svg', url: 'https://www.ruby-lang.org/en/' },
  scss: { name: 'SCSS', icon: 'scss.svg', url: 'https://sass-lang.com/' },
  svn: { name: 'Subversion', icon: 'subversion.svg', url: 'https://subversion.apache.org/' },
  tailwind: { name: 'Tailwind', icon: 'tailwind-css.svg', url: 'https://tailwindcss.com/' },
  temporal: { name: 'Temporal.io', icon: 'temporal.png', url: 'https://temporal.io/' },
  typescript: { name: 'Typescript', icon: 'typescript.svg', url: 'https://www.typescriptlang.org/' },
  vscode: { name: 'VS Code', icon: 'vs-code.svg', url: 'https://code.visualstudio.com/' },
  node: { name: 'Node.js', icon: 'nodejs.svg', url: 'https://nodejs.org' },
  solr: { name: 'Solr', icon: 'solr.svg', url: 'https://solr.apache.org/' },
  rancher: { name: 'Rancher', icon: 'rancher.svg', url: 'https://www.rancher.com/' },
  postgres: { name: 'Postgres', icon: 'postgresql.svg', url: 'https://www.postgresql.org/' },
  'postgres-ha': { name: 'Postgres HA', icon: 'postgresql.svg', url: 'https://www.postgresql.org/' },
  keycloak: { name: 'Keycloak', icon: 'keycloak.png', url: 'https://www.keycloak.org/' },
  bullmq: { name: 'BullMQ', icon: 'bullmq.png', url: 'https://bullmq.io/' },
  php: { name: 'PHP', icon: 'php.svg', url: 'https://www.php.net/' },
  helm: { name: 'Helm', icon: 'helm.svg', url: 'https://helm.sh/' },
  react: { name: 'React', icon: 'react.svg', url: 'https://react.dev/' },
  'objective-c': {
    name: 'Objective-C',
    icon: 'objective-c.svg',
    url: 'https://en.wikipedia.org/wiki/Objective-C',
  },
  mysql: { name: 'Mysql', icon: 'mysql.svg', url: 'https://www.mysql.com/' },
  git: { name: 'Git', icon: 'git.svg', url: 'https://git-scm.com/' },
  kustomize: { name: 'Kustomize', icon: 'kustomize.svg', url: 'https://kustomize.io/' },

  'oauth-proxy': {
    name: 'OAuth2 Proxy',
    icon: 'oauth2-proxy.svg',
    url: 'https://oauth2-proxy.github.io/oauth2-proxy/',
  },
  'cert-manager': { name: 'Cert Manager', icon: 'cert-manager.png', url: 'https://cert-manager.io/' },
  'sealed-secrets': {
    name: 'Sealed Secrets',
    icon: 'sealed-secrets.png',
    url: 'https://github.com/bitnami-labs/sealed-secrets',
  },
  nextjs: { name: 'Next.JS', icon: 'nextjs.svg', url: 'https://nextjs.org/' },
  github: { name: 'Github', icon: 'github.svg', url: 'https://github.com/' },
  'github-action-runner': {
    name: 'Github Action Runner',
    icon: 'githubactions.svg',
    url: 'https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners',
  },
  maven: { name: 'Maven', icon: 'maven.svg', url: 'https://maven.apache.org/' },
  intellij: { name: 'IntelliJ IDEA', icon: 'intellij-idea.svg', url: 'https://www.jetbrains.com/idea/' },
  confluence: {
    name: 'Confluence',
    icon: 'confluence.svg',
    url: 'https://www.atlassian.com/software/confluence',
  },
  'github-actions': {
    name: 'Github Actions',
    icon: 'githubactions.svg',
    url: 'https://docs.github.com/en/actions',
  },
  rabbitmq: { name: 'RabbitMQ', icon: 'rabbitmq.svg', url: 'https://www.rabbitmq.com/' },
  terraform: { name: 'TerraForm', icon: 'terraform.svg', url: 'https://www.terraform.io/' },
  heroku: { name: 'Heroku', icon: 'heroku.svg', url: 'https://www.heroku.com/' },
  aws: {
    name: 'AWS',
    icon: 'aws.svg',
    url: 'https://aws.amazon.com/',
  },
  gcp: {
    name: 'Google Cloud Platform',
    icon: 'google-cloud.svg',
    url: 'https://cloud.google.com',
  },
  azure: { name: 'Azure', icon: 'azure.svg', url: 'https://azure.microsoft.com/' },
  storybook: { name: 'Storybook', icon: 'storybook.svg', url: 'https://storybook.js.org/' },
  jest: { name: 'Jest', icon: 'jest.svg', url: 'https://jestjs.io/' },
  webpack: { name: 'Webpack', icon: 'webpack.svg', url: 'https://webpack.js.org/' },
  vitest: { name: 'Vitest', icon: 'vitest.svg', url: 'https://vitest.dev/' },
  swc: { name: 'SWC', icon: 'swc.svg', url: 'https://swc.rs/' },
  wordpress: { name: 'Wordpress', icon: 'wordpress.svg', url: 'https://wordpress.org/' },
  magnolia: { name: 'Magnolia', icon: 'magnolia.png', url: 'https://www.magnolia-cms.com/' },
  aem: {
    name: 'Adobe Experience Manager',
    icon: 'adobe-experience-manager.svg',
    url: 'https://business.adobe.com/uk/products/experience-manager/adobe-experience-manager.html',
  },
  typeorm: {
    name: 'TypeORM',
    icon: 'typeorm.svg',
    url: 'https://typeorm.io/',
  },
};
