apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-philiplehmann
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-philiplehmann
  template:
    metadata:
      labels:
        app: cv-philiplehmann
    spec:
      imagePullSecrets:
        - name: docker-registry-harbor
      initContainers:
        - name: pdf-dir-
          image: debian:bookworm-slim
          command:
            - chown
            - -R
            - 1000:1000
            - /app/pdf
          volumeMounts:
            - name: pdf
              mountPath: /app/pdf
      containers:
        - name: cv-philiplehmann
          image: harbor.riwi.dev/philiplehmann/cv:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: SITE_URL
              value: https://cv.philiplehmann.ch
            - name: NODE_ENV
              value: production
            - name: PUPPETEER_API_URL
              value: https://puppeteer.api.datage.ch
          envFrom:
            - secretRef:
                name: minio-secret
            - secretRef:
                name: google-analytics-secret
            - secretRef:
                name: rollbar-secret
                
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "150Mi"
              cpu: "0.1"
            limits:
              memory: "300Mi"
              cpu: "1"
          command:
            - node
          args:
            - --max-old-space-size=250
            - node_modules/.bin/next
            - start
          volumeMounts:
            - name: pdf
              mountPath: /app/pdf
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1001
            capabilities: {}
          livenessProbe:
            httpGet:
              path: /api/health/liveness_check
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health/readiness_check
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          startupProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5

      restartPolicy: Always
      volumes:
        - name: pdf
          emptyDir:
            sizeLimit: 20Mi