apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-philiplehmann
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  rules:
  - host: cv.philiplehmann.ch
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: cv-philiplehmann
            port:
              number: 3000
  tls:
  - hosts:
    - cv.philiplehmann.ch
    secretName: cv-philiplehmann-cert


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: philiplehmann
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 $scheme://cv.philiplehmann.ch$request_uri;
spec:
  ingressClassName: nginx
  rules:
  - host: philiplehmann.ch
  - host: www.philiplehmann.ch
  tls:
  - hosts:
    - philiplehmann.ch
    - www.philiplehmann.ch
    secretName: philiplehmann-cert