apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cv-philiplehmann
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    # nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/24, 109.202.219.21"

spec:
  rules:
  - host: cv.philiplehmann.ch
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: cv-philiplehmann
            port:
              number: 3000
  tls:
  - hosts:
    - cv.philiplehmann.ch
    secretName: cv-philiplehmann-cert
