name: Update Sites in Monorepo

on: [push]
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
        curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{secrets.HEROKU_MONOREPO_TOKEN}}" \
          https://api.github.com/repos/philiplehmann/heroku-monorepo/actions/workflows/28019820/dispatches \
          -d '{"ref":"main"}'