name: Update Sites in Monorepo

on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'philiplehmann',
            repo: 'heroku-monorepo',
            workflow_id: 'update-sites.yml',
            ref: 'main'
          })
